"""update_item_physical_fields

Revision ID: 2d45e41c796d
Revises: 9d7517ab80ac
Create Date: 2026-05-20 20:39:41.662234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d45e41c796d'
down_revision: Union[str, Sequence[str], None] = '9d7517ab80ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('width', sa.Integer(), server_default='10', nullable=False))
    op.add_column('items', sa.Column('height', sa.Integer(), server_default='10', nullable=False))
    op.add_column('items', sa.Column('length', sa.Integer(), server_default='10', nullable=False))
    op.add_column('items', sa.Column('weight_grams', sa.Integer(), server_default='500', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'weight_grams')
    op.drop_column('items', 'length')
    op.drop_column('items', 'height')
    op.drop_column('items', 'width')
    # ### end Alembic commands ###
