"""add_prices_to_order

Revision ID: 87de986805fa
Revises: 2d45e41c796d
Create Date: 2026-05-20 21:02:58.834444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "87de986805fa"
down_revision: Union[str, Sequence[str], None] = "2d45e41c796d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column("orders", sa.Column("total_price", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("delivery_price", sa.Integer(), nullable=True))

    op.execute("UPDATE orders SET total_price = 0 WHERE total_price IS NULL")
    op.execute("UPDATE orders SET delivery_price = 0 WHERE delivery_price IS NULL")

    op.alter_column("orders", "total_price", nullable=False)
    op.alter_column("orders", "delivery_price", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "delivery_price")
    op.drop_column("orders", "total_price")
    # ### end Alembic commands ###
