"""add_courier_id_to_orders

Revision ID: c6fe756ebef3
Revises: b3ed8bf714dd
Create Date: 2026-05-20 18:54:03.385213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fe756ebef3'
down_revision: Union[str, Sequence[str], None] = 'b3ed8bf714dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['courier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'courier_id')
    # ### end Alembic commands ###
