"""add order status

Revision ID: d376c7d48abe
Revises: c6fe756ebef3
Create Date: 2026-05-20 19:10:35.335179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d376c7d48abe"
down_revision: Union[str, Sequence[str], None] = "c6fe756ebef3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    order_status_enum = sa.Enum(
        "NEW", "ACCEPTED", "IN_DELIVERY", "DELIVERED", "CANCELLED", name="orderstatus"
    )
    order_status_enum.create(op.get_bind())

    op.add_column(
        "orders",
        sa.Column("status", order_status_enum, nullable=False, server_default="NEW"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "status")
    # ### end Alembic commands ###
