"""Add title to orders table

Revision ID: e9b5797dfd6e
Revises: 7135b5190e39
Create Date: 2026-04-29 23:29:02.339230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b5797dfd6e'
down_revision: Union[str, Sequence[str], None] = '7135b5190e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'title')
    # ### end Alembic commands ###
